project:
  type: website

website:
  title: "Docs"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: notes.qmd
        text: notes
      - href: projects.qmd
        text: projects

format:
  html:
    theme: cyborg
    toc: true



