on:
  push:
    branches:
      - main
    paths:
      - "docs/**"

name: Render and Publish

permissions:
  contents: write
  pages: write

jobs:
  docs-render-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          #cache: "pip"

      - name: Install Jupyter Notebook
        run: pip install jupyter

      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
